"""empty message

Revision ID: 72baaeb881f4
Revises: ae49cd2e8e65
Create Date: 2022-09-01 00:09:43.999259

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72baaeb881f4'
down_revision = 'ae49cd2e8e65'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jam', sa.Column('on_site_limit', sa.Integer(), nullable=False, default=0))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jam', 'on_site_limit')
    # ### end Alembic commands ###
